#!/usr/bin/bash

# default via 10.10.1.100 dev enp0s25 proto static metric 100
myarr=($(ip route | awk '/default/ {print $5}'))


echo -e "Nic\t IP Addressi\t Gateway"
for nic in "${myarr[@]}"
do
  read IP <<< $( ip addr show ${nic} | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
  read gw  <<< $( ip route | grep ${nic} | awk '/default/ {print $3}')
  echo -e "${nic}\t ${IP}\t${gw}"
done
for nic in "${myarr[@]}"
do
  echo -e "\n${nic} Nameservers (IP4):"
  nmcli device show ${nic} | grep IP4.DNS
done


# read nic gw  <<< $( ip route | awk '/default/ {print $5"  "$3}')
# read IP <<< $( ip addr show ${nic} | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)
# echo -e "Your network device is\t: ${nic}"
# echo -e "Your gateway is\t\t: ${gw}"
# echo -e "\nA list of yor nameservers follows"
# nmcli device show ${nic} | grep IP4.DNS
