#!/bin/bash
echo "--------------------Sysinfo--------------------"
echo -e "\t\"Tell me about this machine\""
echo "-----------------------------------------------"
echo "/etc/issue says :\n $(cat /etc/issue)"
echo "-----------------------------------------------"
echo -e "uname -a says :\n $(uname -a)"
echo "-----------------------------------------------"
echo -e "lsb_release -a says:\n $(lsb_release -a)"
echo "-----------------------------------------------"
echo -e "hostnamectl says:\n $(hostnamectl)"
echo "-----------------------------------------------"
echo -e "dmesg \| grep -i \"linux version\" says:\n\t $(dmesg | grep -i 'linux version')"
echo "-----------------------------------------------"
echo -e "/proc/version says:\n $(cat /proc/version)\n"
echo "-----------------------------------------------"
echo -e "current boot args (/proc/cmdline) says\n\t $( cat /proc/cmdline ) \n"
echo "-----------------------------------------------"
echo "With this script \"There Can Be No Confusion!  "
